version : '3'

services:
  apache:
#    image: httpd:latest
    build: ./docker-build/custom-httpd
    depends_on:
      - tomcat
    ports:
      - "80:80"
    volumes:
      - "./docker-conf/custom-httpd/httpd-proxy.conf:/usr/local/apache2/conf.d/httpd-proxy.conf"
    networks:
      - frontend
    links:
      - tomcat

  # MySQL database shared with tomcat containers.
  tomcat:
#    image: tomcat:latest
    build: ./docker-build/custom-tomcat
    # Environment variables do not appear to be getting loaded the first time Tomcat starts!
    environment: 
      JDBC_URL: jdbc:mariadb://mariadb:3306/jpetstore?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: jpetstore
      JDBC_PASS: jpetstore
      JAVA_OPTS: -Xmx1024m -Xms1024m 
    networks:
      - frontend
      - backend
    volumes:
      - "./docker-conf/custom-tomcat/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
      - "./docker-apps/webapps:/usr/local/tomcat/webapps"
    links:
      - mariadb
      - scouter
 
  # MySQL database shared with tomcat containers.
  scouter:
#    image: scouter
    build: ./docker-build/scouter
    ports:
      - "6100:6100"
    networks:
      - frontend
    volumes:
      - "./docker-data/scouter-data:/usr/local/scouter/server/database" 
      - "./docker-logs/scouter-log:/usr/local/scouter/server/logs" 

  # MySQL database shared with tomcat containers.
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword1234
      MYSQL_DATABASE: jpetstore
      MYSQL_USER: jpetstore
      MYSQL_PASSWORD: jpetstore
    networks:
      - backend
    volumes:
      - "./docker-data/db-init:/docker-entrypoint-initdb.d"
      - "./docker-data/db-data:/var/lib/mysql"
      - "./docker-logs/db-log:/var/log/mysql"

# network layer
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
